server:
  port: 9999
spring:
  application:
    name: pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zroot
    url: jdbc:mysql://localhost:3306/pay?serverTimezone=GMT%2B8
