server:
  port: 9998
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zroot
    url: jdbc:mysql://localhost:3306/order?serverTimezone=GMT%2B8
